<a href="https://colab.research.google.com/github/kupendrav/DS-AI/blob/main/D_1live.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
! pip install numpy

numpy (NUMERICAL PYTHON) is an open source python library thats used in almost every field of science and engineering


id()=**pointer to memory location**

In [ ]:
x=3
id(x)

139508437877040

In [ ]:
y=3
id(y)

139508437877040

above you can see both are sharing same memory loc to diff variable

what are the advantages in array? <br>
faster calculation and computation

In [16]:
import numpy as np
np.__version__

'1.25.2'

In [12]:
import numpy as np
a = np.array([[1,2,3,4,5],[5,6,7,8,9]])
a

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [17]:
np.random.random((3,3))

array([[0.77276118, 0.83533996, 0.55037132],
       [0.47238262, 0.50407674, 0.52125339],
       [0.83797533, 0.19711273, 0.68371395]])

# **Attributes**

In [20]:
x1 = np.random.randint(20,size=(3,3))
x1.data

In [25]:
x1.shape

(3, 3)

In [23]:
x1

array([[10,  1,  5],
       [16,  0, 14],
       [ 3,  6,  2]])

In [24]:
x1[2,1]

6

: start :end

In [26]:
x1[:,:]

array([[10,  1,  5],
       [16,  0, 14],
       [ 3,  6,  2]])

In [27]:
x1[:,2]

array([ 5, 14,  2])

In [29]:
x1[0,0:1]

array([10])